/**
 * Emits supabase/migrations/0003_seed.sql from the app's own data files, so the
 * database and the front-end catalogue cannot drift apart.
 *
 *   npm run seed:sql
 *
 * Re-runnable: every statement is an upsert keyed on the natural key, so running
 * the output twice changes nothing. Stock is only set on first insert — it would
 * be rude to reset live stock levels every time someone re-seeds.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { COLORWAYS } from '../src/data/colorways.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')

/** Postgres string literal, escaping single quotes. */
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const arr = (list) =>
  list && list.length ? `array[${list.map((v) => q(v)).join(', ')}]::text[]` : `'{}'::text[]`
const bool = (v) => (v ? 'true' : 'false')
const int = (v) => (Number.isFinite(Number(v)) ? Math.round(Number(v)) : 0)

const out = []
const say = (s = '') => out.push(s)

say('-- ============================================================================')
say('-- Hijabisaura — 0003: reference data + catalogue')
say('--')
say('-- GENERATED by scripts/generate-seed.mjs. Do not edit by hand; edit the data')
say('-- files under src/data and re-run `npm run seed:sql`.')
say('--')
say('-- Safe to run more than once for products, stock and settings.')
say('--')
say('-- !! DO NOT RUN THIS ONCE YOU HAVE UPLOADED REAL PHOTOGRAPHS !!')
say('-- It replaces product_images wholesale, so it would delete every uploaded')
say('-- URL and put the generated placeholders back. After your first real upload,')
say('-- treat this file as historical and change products in Admin instead.')
say('-- ============================================================================')
say()
say('begin;')
say()

/* ---------------------------------------------------------------- colorways --- */

say('-- The dye card ------------------------------------------------------------')
say('insert into public.colorways (code, name, hex, family, is_light, sort_order) values')
say(
  COLORWAYS.map(
    (c, i) =>
      `  (${q(c.code)}, ${q(c.name)}, ${q(c.hex)}, ${q(c.family)}, ${bool(c.light)}, ${i})`
  ).join(',\n') + ''
)
say('on conflict (code) do update set')
say('  name = excluded.name, hex = excluded.hex,')
say('  family = excluded.family, is_light = excluded.is_light,')
say('  sort_order = excluded.sort_order;')
say()

/* -------------------------------------------------------------- collections --- */

const { COLLECTIONS } = await import('../src/data/collections.js')

say('-- Collections -------------------------------------------------------------')
say(
  'insert into public.collections (slug, name, kicker, blurb, banner, sort_order, published) values'
)
say(
  COLLECTIONS.map(
    (c) =>
      `  (${q(c.slug)}, ${q(c.name)}, ${q(c.kicker)}, ${q(c.blurb)}, ${q(c.banner)}, ${int(
        c.order
      )}, ${bool(c.published)})`
  ).join(',\n')
)
say('on conflict (slug) do update set')
say('  name = excluded.name, kicker = excluded.kicker, blurb = excluded.blurb,')
say('  banner = excluded.banner, sort_order = excluded.sort_order,')
say('  published = excluded.published;')
say()

/* ---------------------------------------------------------------- settings --- */

const { SETTINGS } = await import('../src/data/settings.js')

// brand/payments/shipping/returns/ops are all read by the storefront, so all are
// public. Nothing secret belongs in this table.
say('-- Store settings ----------------------------------------------------------')
say('insert into public.store_settings (key, value, is_public) values')
say(
  Object.entries(SETTINGS)
    .map(([k, v]) => `  (${q(k)}, ${q(JSON.stringify(v))}::jsonb, true)`)
    .join(',\n')
)
say('on conflict (key) do update set value = excluded.value;')
say()

/* ----------------------------------------------------------------- coupons --- */

const { COUPONS } = await import('../src/data/orders.js')

say('-- Coupons ----------------------------------------------------------------')
say(
  'insert into public.coupons (code, kind, value, min_order, active, uses, usage_cap, note, expires_at) values'
)
say(
  COUPONS.map(
    (c) =>
      `  (${q(c.code)}, ${q(c.kind)}, ${int(c.value)}, ${int(c.minOrder)}, ${bool(
        c.active
      )}, ${int(c.uses)}, ${c.cap ? int(c.cap) : 'null'}, ${q(c.note)}, now() + interval '${int(
        c.expiresDaysFromNow
      )} days')`
  ).join(',\n')
)
say('on conflict (code) do update set')
say('  kind = excluded.kind, value = excluded.value, min_order = excluded.min_order,')
say('  active = excluded.active, usage_cap = excluded.usage_cap, note = excluded.note,')
say('  expires_at = excluded.expires_at;')
say()

/* ---------------------------------------------------------------- products --- */

const { PRODUCTS } = await import('../src/data/products.js')

say('-- Products ---------------------------------------------------------------')
for (const p of PRODUCTS) {
  say(`-- ${p.name}`)
  say(`insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  ${q(p.id)}, ${q(p.slug)}, ${q(p.name)}, ${q(p.tagline || '')}, ${q(p.description || '')},
  ${q(p.collection)}, ${q(p.style)}, ${arr(p.occasion)},
  ${int(p.price)}, ${int(p.mrp)}, ${q(p.fabric)}, ${q(p.composition || '')}, ${q(p.weave)}, ${int(p.gsm)},
  ${int(p.size?.w)}, ${int(p.size?.l)}, ${q(p.size?.note || '')}, ${int(p.weight)},
  ${q(p.origin || '')}, ${q(p.care || '')}, ${arr(p.notes)}, ${q(p.warning || '')},
  ${bool(p.pinless)}, ${bool(p.madeToOrder)}, ${bool(p.smallBatch)},
  ${bool(p.featured)}, ${bool(p.published)}, ${int(p.sold)}
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;`)

  p.colorways.forEach((c, ci) => {
    say(`insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values (${q(p.id)}, ${q(c.code)}, ${int(c.stock)}, ${ci})
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;`)

    // Images are replaced wholesale: order is meaningful and a diff would be
    // more trouble than a rewrite.
    say(
      `delete from public.product_images where product_id = ${q(p.id)} and colorway_code = ${q(c.code)};`
    )
    if (c.images.length) {
      say('insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values')
      say(
        c.images
          .map(
            (url, ii) =>
              `  (${q(p.id)}, ${q(c.code)}, ${q(url)}, ${q(`${p.name} in ${c.name}`)}, ${ii})`
          )
          .join(',\n') + ';'
      )
    }
  })
  say()
}

say('commit;')
say()
say('-- Reviews and orders are intentionally NOT seeded. Ninety days of invented')
say('-- trading history is useful in a demo and misleading in a real shop — your')
say('-- dashboard should start empty and fill up with real orders.')

const target = resolve(ROOT, 'supabase/migrations/0003_seed.sql')
mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, out.join('\n') + '\n')

const rows =
  COLORWAYS.length + COLLECTIONS.length + PRODUCTS.length + COUPONS.length + Object.keys(SETTINGS).length
console.log(
  `Wrote supabase/migrations/0003_seed.sql — ${COLORWAYS.length} colourways, ` +
    `${COLLECTIONS.length} collections, ${PRODUCTS.length} products, ` +
    `${COUPONS.length} coupons, ${Object.keys(SETTINGS).length} settings groups (${rows} top-level rows)`
)
