-- ============================================================================
-- Hijabisaura — 0003: reference data + catalogue
--
-- GENERATED by scripts/generate-seed.mjs. Do not edit by hand; edit the data
-- files under src/data and re-run `npm run seed:sql`.
--
-- Safe to run more than once. Stock is set on insert only, so re-seeding
-- never overwrites live stock levels.
-- ============================================================================

begin;

-- The dye card ------------------------------------------------------------
insert into public.colorways (code, name, hex, family, is_light, sort_order) values
  ('HA-01', 'Midnight Plum', '#2A1F33', 'purple', false, 0),
  ('HA-02', 'Ink Rose', '#7A2F45', 'red', false, 1),
  ('HA-03', 'Aura Rose', '#B98D86', 'pink', true, 2),
  ('HA-04', 'Jade Deep', '#1F6B5C', 'green', false, 3),
  ('HA-05', 'Sage Mist', '#A8B5A2', 'green', true, 4),
  ('HA-06', 'Oat Chalk', '#E4DED3', 'neutral', true, 5),
  ('HA-07', 'Sand Dune', '#C9B79C', 'neutral', true, 6),
  ('HA-08', 'Camel', '#B08A5E', 'brown', true, 7),
  ('HA-09', 'Saffron', '#D8A03D', 'yellow', true, 8),
  ('HA-10', 'Terracotta', '#B4593A', 'orange', false, 9),
  ('HA-11', 'Bordeaux', '#6E2231', 'red', false, 10),
  ('HA-12', 'Blush Pearl', '#E7C8C4', 'pink', true, 11),
  ('HA-13', 'Lavender Haze', '#B3A5C6', 'purple', true, 12),
  ('HA-14', 'Steel Blue', '#5B7290', 'blue', false, 13),
  ('HA-15', 'Navy Ink', '#23314C', 'blue', false, 14),
  ('HA-16', 'Teal Slate', '#3A6B72', 'blue', false, 15),
  ('HA-17', 'Olive Bronze', '#6E6A3C', 'green', false, 16),
  ('HA-18', 'Charcoal', '#3B3A3E', 'neutral', false, 17),
  ('HA-19', 'Pearl White', '#EFEDEA', 'neutral', true, 18),
  ('HA-20', 'Onyx', '#1A181C', 'neutral', false, 19),
  ('HA-21', 'Mocha', '#6B4A3C', 'brown', false, 20),
  ('HA-22', 'Rose Gold', '#D9A99A', 'pink', true, 21)
on conflict (code) do update set
  name = excluded.name, hex = excluded.hex,
  family = excluded.family, is_light = excluded.is_light,
  sort_order = excluded.sort_order;

-- Collections -------------------------------------------------------------
insert into public.collections (slug, name, kicker, blurb, banner, sort_order, published) values
  ('everyday-modal', 'Everyday Modal', 'Worn Monday to Thursday', 'Soft twills and modals in the 110–145 GSM band. Opaque, cool, and cut long enough that you stop thinking about it by 9am.', '/img/collections/everyday-modal.svg', 1, true),
  ('crinkle-chiffon', 'Crinkle & Chiffon', 'The no-iron drawer', 'Texture set into the cloth under heat, so it survives the wash and the suitcase. Light, fast-drying, and mostly pinless.', '/img/collections/crinkle-chiffon.svg', 2, true),
  ('occasion-satin', 'Occasion & Satin', 'For the evening you dressed up for', 'High-lustre satins and shimmer georgettes cut two metres long, for drapes that need to hold a shape in photographs.', '/img/collections/occasion-satin.svg', 3, true),
  ('jersey-instant', 'Jersey & Instant', 'Out the door in six seconds', 'Stretch knits from 180 to 240 GSM, plus pre-sewn instants with the under-cap built in. Nothing here needs a pin.', '/img/collections/jersey-instant.svg', 4, true),
  ('bridal-atelier', 'Bridal Atelier', 'Made to order, signed by hand', 'Silk tulle worked by one karigar over nine to fourteen days. We cut nothing before you ask, and we sign what we send.', '/img/collections/bridal-atelier.svg', 5, true),
  ('essentials', 'Essentials', 'The layer underneath', 'Under-caps that do not print a line on your forehead, and magnets strong enough for a 240 GSM jersey.', '/img/collections/essentials.svg', 6, true)
on conflict (slug) do update set
  name = excluded.name, kicker = excluded.kicker, blurb = excluded.blurb,
  banner = excluded.banner, sort_order = excluded.sort_order,
  published = excluded.published;

-- Store settings ----------------------------------------------------------
insert into public.store_settings (key, value, is_public) values
  ('brand', '{"name":"Hijabisaura","tagline":"Your Aura, Your Style.","promise":"Hijabs chosen by how they fall","email":"salaam@hijabisaura.in","phone":"+91 98200 41102","whatsapp":"919820041102","address":"Unit 4, Mehrab House, Mohammed Ali Road, Mumbai 400003","gstin":"27AABCH1234K1ZQ","instagram":"hijabisaura","instagramUrl":"https://instagram.com/hijabisaura"}'::jsonb, true),
  ('payments', '{"upiVpa":"hijabisaura@okicici","upiPayeeName":"Hijabisaura Retail","upiEnabled":true,"codEnabled":true,"codFee":49,"codMinOrder":499,"codMaxOrder":7000,"cardsEnabled":false,"prepaidDiscountPct":5}'::jsonb, true),
  ('shipping', '{"freeAbove":999,"standardFee":79,"expressFee":199,"standardDays":"4–7 working days","expressDays":"2–3 working days","dispatchNote":"Orders placed before 2pm IST dispatch the same day."}'::jsonb, true),
  ('returns', '{"windowDays":7,"exchangeOnly":false,"note":"Unworn, unwashed, tags on. Bridal and made-to-order pieces are final sale."}'::jsonb, true),
  ('ops', '{"lowStockThreshold":10,"currency":"INR","locale":"en-IN"}'::jsonb, true)
on conflict (key) do update set value = excluded.value;

-- Coupons ----------------------------------------------------------------
insert into public.coupons (code, kind, value, min_order, active, uses, usage_cap, note, expires_at) values
  ('AURA10', 'percent', 10, 999, true, 412, 2000, 'Sitewide, first order', now() + interval '45 days'),
  ('UPI5', 'percent', 5, 0, true, 1908, null, 'Auto-applied on prepaid — stacks with nothing else', now() + interval '365 days'),
  ('MODAL200', 'flat', 200, 1499, true, 88, 500, 'Everyday Modal collection only', now() + interval '18 days'),
  ('EID24', 'percent', 15, 1999, false, 1204, 1500, 'Expired — Eid campaign', now() + interval '-60 days'),
  ('FREESHIP', 'shipping', 0, 599, true, 640, null, 'Waives standard shipping', now() + interval '90 days')
on conflict (code) do update set
  kind = excluded.kind, value = excluded.value, min_order = excluded.min_order,
  active = excluded.active, usage_cap = excluded.usage_cap, note = excluded.note,
  expires_at = excluded.expires_at;

-- Products ---------------------------------------------------------------
-- Kaanza Crinkle Chiffon
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-kaanza-crinkle', 'kaanza-crinkle-chiffon', 'Kaanza Crinkle Chiffon', 'The one that never needs an iron', 'A crinkle set into the cloth under heat, so it survives the wash and the suitcase. It grips itself, which is why most people wear this one without a single pin.',
  'crinkle-chiffon', 'rectangle', array['everyday', 'work', 'travel']::text[],
  899, 1299, 'Crinkle chiffon', '100% polyester chiffon, mechanically crinkled', 'plain', 62,
  75, 185, '', 88,
  'Surat, Gujarat', 'Hand wash cold. Never iron — the crinkle is the finish.', array['Crinkle is permanent — it will not fall out in the wash', 'Grips without pins on most fabrics', 'Cut long enough to wrap twice and still drape']::text[], '',
  true, false, false,
  true, true, 3180
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-kaanza-crinkle', 'HA-13', 24, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-kaanza-crinkle' and colorway_code = 'HA-13';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-kaanza-crinkle', 'HA-13', '/img/fabric/ha-13-drape.svg', 'Kaanza Crinkle Chiffon in Lavender Haze', 0),
  ('p-kaanza-crinkle', 'HA-13', '/img/fabric/ha-13-styled.svg', 'Kaanza Crinkle Chiffon in Lavender Haze', 1),
  ('p-kaanza-crinkle', 'HA-13', '/img/fabric/ha-13-flat.svg', 'Kaanza Crinkle Chiffon in Lavender Haze', 2),
  ('p-kaanza-crinkle', 'HA-13', '/img/fabric/ha-13-macro.svg', 'Kaanza Crinkle Chiffon in Lavender Haze', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-kaanza-crinkle', 'HA-06', 18, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-kaanza-crinkle' and colorway_code = 'HA-06';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-kaanza-crinkle', 'HA-06', '/img/fabric/ha-06-drape.svg', 'Kaanza Crinkle Chiffon in Oat Chalk', 0),
  ('p-kaanza-crinkle', 'HA-06', '/img/fabric/ha-06-styled.svg', 'Kaanza Crinkle Chiffon in Oat Chalk', 1),
  ('p-kaanza-crinkle', 'HA-06', '/img/fabric/ha-06-flat.svg', 'Kaanza Crinkle Chiffon in Oat Chalk', 2),
  ('p-kaanza-crinkle', 'HA-06', '/img/fabric/ha-06-macro.svg', 'Kaanza Crinkle Chiffon in Oat Chalk', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-kaanza-crinkle', 'HA-01', 31, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-kaanza-crinkle' and colorway_code = 'HA-01';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-kaanza-crinkle', 'HA-01', '/img/fabric/ha-01-drape.svg', 'Kaanza Crinkle Chiffon in Midnight Plum', 0),
  ('p-kaanza-crinkle', 'HA-01', '/img/fabric/ha-01-styled.svg', 'Kaanza Crinkle Chiffon in Midnight Plum', 1),
  ('p-kaanza-crinkle', 'HA-01', '/img/fabric/ha-01-flat.svg', 'Kaanza Crinkle Chiffon in Midnight Plum', 2),
  ('p-kaanza-crinkle', 'HA-01', '/img/fabric/ha-01-macro.svg', 'Kaanza Crinkle Chiffon in Midnight Plum', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-kaanza-crinkle', 'HA-11', 7, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-kaanza-crinkle' and colorway_code = 'HA-11';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-kaanza-crinkle', 'HA-11', '/img/fabric/ha-11-drape.svg', 'Kaanza Crinkle Chiffon in Bordeaux', 0),
  ('p-kaanza-crinkle', 'HA-11', '/img/fabric/ha-11-styled.svg', 'Kaanza Crinkle Chiffon in Bordeaux', 1),
  ('p-kaanza-crinkle', 'HA-11', '/img/fabric/ha-11-flat.svg', 'Kaanza Crinkle Chiffon in Bordeaux', 2),
  ('p-kaanza-crinkle', 'HA-11', '/img/fabric/ha-11-macro.svg', 'Kaanza Crinkle Chiffon in Bordeaux', 3);

-- Noor Premium Jersey
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-noor-jersey', 'noor-premium-jersey', 'Noor Premium Jersey', 'Pull on, tuck once, leave', 'Four percent elastane is the whole trick — enough stretch to sit flat around the crown without a cap underneath, not enough to sag by evening.',
  'jersey-instant', 'rectangle', array['everyday', 'sport', 'work']::text[],
  749, 999, 'Cotton-modal jersey', '62% cotton, 34% modal, 4% elastane', 'jersey', 180,
  70, 175, '', 165,
  'Tiruppur, Tamil Nadu', 'Machine wash cold, tumble low. Reshape while damp.', array['Opaque enough to skip an under-cap', 'Holds shape through a full day', 'Breathes — the modal does the work']::text[], '',
  true, false, false,
  true, true, 5240
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-noor-jersey', 'HA-18', 42, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-noor-jersey' and colorway_code = 'HA-18';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-noor-jersey', 'HA-18', '/img/fabric/ha-18-drape.svg', 'Noor Premium Jersey in Charcoal', 0),
  ('p-noor-jersey', 'HA-18', '/img/fabric/ha-18-styled.svg', 'Noor Premium Jersey in Charcoal', 1),
  ('p-noor-jersey', 'HA-18', '/img/fabric/ha-18-flat.svg', 'Noor Premium Jersey in Charcoal', 2),
  ('p-noor-jersey', 'HA-18', '/img/fabric/ha-18-macro.svg', 'Noor Premium Jersey in Charcoal', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-noor-jersey', 'HA-20', 38, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-noor-jersey' and colorway_code = 'HA-20';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-noor-jersey', 'HA-20', '/img/fabric/ha-20-drape.svg', 'Noor Premium Jersey in Onyx', 0),
  ('p-noor-jersey', 'HA-20', '/img/fabric/ha-20-styled.svg', 'Noor Premium Jersey in Onyx', 1),
  ('p-noor-jersey', 'HA-20', '/img/fabric/ha-20-flat.svg', 'Noor Premium Jersey in Onyx', 2),
  ('p-noor-jersey', 'HA-20', '/img/fabric/ha-20-macro.svg', 'Noor Premium Jersey in Onyx', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-noor-jersey', 'HA-15', 21, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-noor-jersey' and colorway_code = 'HA-15';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-noor-jersey', 'HA-15', '/img/fabric/ha-15-drape.svg', 'Noor Premium Jersey in Navy Ink', 0),
  ('p-noor-jersey', 'HA-15', '/img/fabric/ha-15-styled.svg', 'Noor Premium Jersey in Navy Ink', 1),
  ('p-noor-jersey', 'HA-15', '/img/fabric/ha-15-flat.svg', 'Noor Premium Jersey in Navy Ink', 2),
  ('p-noor-jersey', 'HA-15', '/img/fabric/ha-15-macro.svg', 'Noor Premium Jersey in Navy Ink', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-noor-jersey', 'HA-21', 14, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-noor-jersey' and colorway_code = 'HA-21';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-noor-jersey', 'HA-21', '/img/fabric/ha-21-drape.svg', 'Noor Premium Jersey in Mocha', 0),
  ('p-noor-jersey', 'HA-21', '/img/fabric/ha-21-styled.svg', 'Noor Premium Jersey in Mocha', 1),
  ('p-noor-jersey', 'HA-21', '/img/fabric/ha-21-flat.svg', 'Noor Premium Jersey in Mocha', 2),
  ('p-noor-jersey', 'HA-21', '/img/fabric/ha-21-macro.svg', 'Noor Premium Jersey in Mocha', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-noor-jersey', 'HA-19', 9, 4)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-noor-jersey' and colorway_code = 'HA-19';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-noor-jersey', 'HA-19', '/img/fabric/ha-19-drape.svg', 'Noor Premium Jersey in Pearl White', 0),
  ('p-noor-jersey', 'HA-19', '/img/fabric/ha-19-styled.svg', 'Noor Premium Jersey in Pearl White', 1),
  ('p-noor-jersey', 'HA-19', '/img/fabric/ha-19-flat.svg', 'Noor Premium Jersey in Pearl White', 2),
  ('p-noor-jersey', 'HA-19', '/img/fabric/ha-19-macro.svg', 'Noor Premium Jersey in Pearl White', 3);

-- Mahd Modal Everyday
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-mahd-modal', 'mahd-modal-everyday', 'Mahd Modal Everyday', 'Our house cloth', 'The one we would pick if we could only keep one. A soft twill that falls in long unbroken lines instead of breaking into small folds — which is what makes it read as tailored rather than casual.',
  'everyday-modal', 'rectangle', array['everyday', 'work']::text[],
  999, 1399, 'Bamboo modal', '95% bamboo modal, 5% spandex', 'twill', 130,
  75, 190, '', 148,
  'Ludhiana, Punjab', 'Machine wash cold on gentle. Line dry in shade.', array['Falls in long lines, not small folds', 'Cool against the skin in summer', 'Takes a pin cleanly without leaving a hole']::text[], '',
  false, false, false,
  true, true, 8930
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-mahd-modal', 'HA-06', 55, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-mahd-modal' and colorway_code = 'HA-06';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-mahd-modal', 'HA-06', '/img/fabric/ha-06-drape.svg', 'Mahd Modal Everyday in Oat Chalk', 0),
  ('p-mahd-modal', 'HA-06', '/img/fabric/ha-06-styled.svg', 'Mahd Modal Everyday in Oat Chalk', 1),
  ('p-mahd-modal', 'HA-06', '/img/fabric/ha-06-flat.svg', 'Mahd Modal Everyday in Oat Chalk', 2),
  ('p-mahd-modal', 'HA-06', '/img/fabric/ha-06-macro.svg', 'Mahd Modal Everyday in Oat Chalk', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-mahd-modal', 'HA-04', 34, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-mahd-modal' and colorway_code = 'HA-04';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-mahd-modal', 'HA-04', '/img/fabric/ha-04-drape.svg', 'Mahd Modal Everyday in Jade Deep', 0),
  ('p-mahd-modal', 'HA-04', '/img/fabric/ha-04-styled.svg', 'Mahd Modal Everyday in Jade Deep', 1),
  ('p-mahd-modal', 'HA-04', '/img/fabric/ha-04-flat.svg', 'Mahd Modal Everyday in Jade Deep', 2),
  ('p-mahd-modal', 'HA-04', '/img/fabric/ha-04-macro.svg', 'Mahd Modal Everyday in Jade Deep', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-mahd-modal', 'HA-01', 28, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-mahd-modal' and colorway_code = 'HA-01';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-mahd-modal', 'HA-01', '/img/fabric/ha-01-drape.svg', 'Mahd Modal Everyday in Midnight Plum', 0),
  ('p-mahd-modal', 'HA-01', '/img/fabric/ha-01-styled.svg', 'Mahd Modal Everyday in Midnight Plum', 1),
  ('p-mahd-modal', 'HA-01', '/img/fabric/ha-01-flat.svg', 'Mahd Modal Everyday in Midnight Plum', 2),
  ('p-mahd-modal', 'HA-01', '/img/fabric/ha-01-macro.svg', 'Mahd Modal Everyday in Midnight Plum', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-mahd-modal', 'HA-03', 19, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-mahd-modal' and colorway_code = 'HA-03';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-mahd-modal', 'HA-03', '/img/fabric/ha-03-drape.svg', 'Mahd Modal Everyday in Aura Rose', 0),
  ('p-mahd-modal', 'HA-03', '/img/fabric/ha-03-styled.svg', 'Mahd Modal Everyday in Aura Rose', 1),
  ('p-mahd-modal', 'HA-03', '/img/fabric/ha-03-flat.svg', 'Mahd Modal Everyday in Aura Rose', 2),
  ('p-mahd-modal', 'HA-03', '/img/fabric/ha-03-macro.svg', 'Mahd Modal Everyday in Aura Rose', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-mahd-modal', 'HA-15', 41, 4)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-mahd-modal' and colorway_code = 'HA-15';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-mahd-modal', 'HA-15', '/img/fabric/ha-15-drape.svg', 'Mahd Modal Everyday in Navy Ink', 0),
  ('p-mahd-modal', 'HA-15', '/img/fabric/ha-15-styled.svg', 'Mahd Modal Everyday in Navy Ink', 1),
  ('p-mahd-modal', 'HA-15', '/img/fabric/ha-15-flat.svg', 'Mahd Modal Everyday in Navy Ink', 2),
  ('p-mahd-modal', 'HA-15', '/img/fabric/ha-15-macro.svg', 'Mahd Modal Everyday in Navy Ink', 3);

-- Silk Route Satin
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-silk-route-satin', 'silk-route-satin', 'Silk Route Satin', 'For the evening you dressed up for', 'Satin on one face, crepe on the other, so you choose your own finish on the day — full lustre out, or matte out with the shine only showing in the folds.',
  'occasion-satin', 'rectangle', array['occasion', 'wedding', 'eid']::text[],
  1699, 2399, 'Satin-back crepe', '100% viscose satin', 'satin', 105,
  70, 200, '', 132,
  'Varanasi, Uttar Pradesh', 'Dry clean, or hand wash cold with no wringing.', array['Reversible: satin face or crepe face', 'Slippery — this one wants pins', 'Two metres, cut for a styled drape']::text[], '',
  false, false, false,
  true, true, 1420
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-silk-route-satin', 'HA-11', 16, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-silk-route-satin' and colorway_code = 'HA-11';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-silk-route-satin', 'HA-11', '/img/fabric/ha-11-drape.svg', 'Silk Route Satin in Bordeaux', 0),
  ('p-silk-route-satin', 'HA-11', '/img/fabric/ha-11-styled.svg', 'Silk Route Satin in Bordeaux', 1),
  ('p-silk-route-satin', 'HA-11', '/img/fabric/ha-11-flat.svg', 'Silk Route Satin in Bordeaux', 2),
  ('p-silk-route-satin', 'HA-11', '/img/fabric/ha-11-macro.svg', 'Silk Route Satin in Bordeaux', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-silk-route-satin', 'HA-01', 22, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-silk-route-satin' and colorway_code = 'HA-01';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-silk-route-satin', 'HA-01', '/img/fabric/ha-01-drape.svg', 'Silk Route Satin in Midnight Plum', 0),
  ('p-silk-route-satin', 'HA-01', '/img/fabric/ha-01-styled.svg', 'Silk Route Satin in Midnight Plum', 1),
  ('p-silk-route-satin', 'HA-01', '/img/fabric/ha-01-flat.svg', 'Silk Route Satin in Midnight Plum', 2),
  ('p-silk-route-satin', 'HA-01', '/img/fabric/ha-01-macro.svg', 'Silk Route Satin in Midnight Plum', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-silk-route-satin', 'HA-16', 11, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-silk-route-satin' and colorway_code = 'HA-16';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-silk-route-satin', 'HA-16', '/img/fabric/ha-16-drape.svg', 'Silk Route Satin in Teal Slate', 0),
  ('p-silk-route-satin', 'HA-16', '/img/fabric/ha-16-styled.svg', 'Silk Route Satin in Teal Slate', 1),
  ('p-silk-route-satin', 'HA-16', '/img/fabric/ha-16-flat.svg', 'Silk Route Satin in Teal Slate', 2),
  ('p-silk-route-satin', 'HA-16', '/img/fabric/ha-16-macro.svg', 'Silk Route Satin in Teal Slate', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-silk-route-satin', 'HA-09', 8, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-silk-route-satin' and colorway_code = 'HA-09';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-silk-route-satin', 'HA-09', '/img/fabric/ha-09-drape.svg', 'Silk Route Satin in Saffron', 0),
  ('p-silk-route-satin', 'HA-09', '/img/fabric/ha-09-styled.svg', 'Silk Route Satin in Saffron', 1),
  ('p-silk-route-satin', 'HA-09', '/img/fabric/ha-09-flat.svg', 'Silk Route Satin in Saffron', 2),
  ('p-silk-route-satin', 'HA-09', '/img/fabric/ha-09-macro.svg', 'Silk Route Satin in Saffron', 3);

-- Zahra Bamboo Viscose
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-zahra-viscose', 'zahra-bamboo-viscose', 'Zahra Bamboo Viscose', 'Built for a 40° afternoon', 'Bamboo viscose moves heat away from the skin faster than cotton at the same weight. In a Chennai summer that is not a marketing line, it is the reason you can wear this at 2pm.',
  'everyday-modal', 'rectangle', array['everyday', 'summer', 'travel']::text[],
  849, 1199, 'Bamboo viscose', '100% bamboo viscose', 'plain', 110,
  72, 180, '', 118,
  'Coimbatore, Tamil Nadu', 'Hand wash cold. Dry flat in shade.', array['Moves heat away faster than cotton', 'Naturally low static', 'Light enough to layer']::text[], '',
  false, false, false,
  false, true, 4110
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-zahra-viscose', 'HA-05', 29, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-zahra-viscose' and colorway_code = 'HA-05';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-zahra-viscose', 'HA-05', '/img/fabric/ha-05-drape.svg', 'Zahra Bamboo Viscose in Sage Mist', 0),
  ('p-zahra-viscose', 'HA-05', '/img/fabric/ha-05-styled.svg', 'Zahra Bamboo Viscose in Sage Mist', 1),
  ('p-zahra-viscose', 'HA-05', '/img/fabric/ha-05-flat.svg', 'Zahra Bamboo Viscose in Sage Mist', 2),
  ('p-zahra-viscose', 'HA-05', '/img/fabric/ha-05-macro.svg', 'Zahra Bamboo Viscose in Sage Mist', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-zahra-viscose', 'HA-19', 33, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-zahra-viscose' and colorway_code = 'HA-19';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-zahra-viscose', 'HA-19', '/img/fabric/ha-19-drape.svg', 'Zahra Bamboo Viscose in Pearl White', 0),
  ('p-zahra-viscose', 'HA-19', '/img/fabric/ha-19-styled.svg', 'Zahra Bamboo Viscose in Pearl White', 1),
  ('p-zahra-viscose', 'HA-19', '/img/fabric/ha-19-flat.svg', 'Zahra Bamboo Viscose in Pearl White', 2),
  ('p-zahra-viscose', 'HA-19', '/img/fabric/ha-19-macro.svg', 'Zahra Bamboo Viscose in Pearl White', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-zahra-viscose', 'HA-07', 24, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-zahra-viscose' and colorway_code = 'HA-07';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-zahra-viscose', 'HA-07', '/img/fabric/ha-07-drape.svg', 'Zahra Bamboo Viscose in Sand Dune', 0),
  ('p-zahra-viscose', 'HA-07', '/img/fabric/ha-07-styled.svg', 'Zahra Bamboo Viscose in Sand Dune', 1),
  ('p-zahra-viscose', 'HA-07', '/img/fabric/ha-07-flat.svg', 'Zahra Bamboo Viscose in Sand Dune', 2),
  ('p-zahra-viscose', 'HA-07', '/img/fabric/ha-07-macro.svg', 'Zahra Bamboo Viscose in Sand Dune', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-zahra-viscose', 'HA-12', 17, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-zahra-viscose' and colorway_code = 'HA-12';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-zahra-viscose', 'HA-12', '/img/fabric/ha-12-drape.svg', 'Zahra Bamboo Viscose in Blush Pearl', 0),
  ('p-zahra-viscose', 'HA-12', '/img/fabric/ha-12-styled.svg', 'Zahra Bamboo Viscose in Blush Pearl', 1),
  ('p-zahra-viscose', 'HA-12', '/img/fabric/ha-12-flat.svg', 'Zahra Bamboo Viscose in Blush Pearl', 2),
  ('p-zahra-viscose', 'HA-12', '/img/fabric/ha-12-macro.svg', 'Zahra Bamboo Viscose in Blush Pearl', 3);

-- Ayla Instant Slip-On
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-ayla-instant', 'ayla-instant-slip-on', 'Ayla Instant Slip-On', 'Six seconds, no mirror', 'Sewn into its final shape with the under-cap built in. Nothing to wrap, nothing to pin — you pull it on and go. The trade is that the drape is fixed; you cannot restyle it.',
  'jersey-instant', 'instant', array['everyday', 'sport', 'travel']::text[],
  699, 949, 'Ribbed jersey', '92% viscose, 8% elastane', 'jersey', 195,
  0, 0, 'One size, pre-sewn', 140,
  'Tiruppur, Tamil Nadu', 'Machine wash cold in a mesh bag.', array['Under-cap sewn in', 'Fixed drape — cannot be restyled', 'The one to keep by the door']::text[], '',
  true, false, false,
  false, true, 6350
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-ayla-instant', 'HA-20', 47, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-ayla-instant' and colorway_code = 'HA-20';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-ayla-instant', 'HA-20', '/img/fabric/ha-20-drape.svg', 'Ayla Instant Slip-On in Onyx', 0),
  ('p-ayla-instant', 'HA-20', '/img/fabric/ha-20-styled.svg', 'Ayla Instant Slip-On in Onyx', 1),
  ('p-ayla-instant', 'HA-20', '/img/fabric/ha-20-flat.svg', 'Ayla Instant Slip-On in Onyx', 2),
  ('p-ayla-instant', 'HA-20', '/img/fabric/ha-20-macro.svg', 'Ayla Instant Slip-On in Onyx', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-ayla-instant', 'HA-18', 39, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-ayla-instant' and colorway_code = 'HA-18';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-ayla-instant', 'HA-18', '/img/fabric/ha-18-drape.svg', 'Ayla Instant Slip-On in Charcoal', 0),
  ('p-ayla-instant', 'HA-18', '/img/fabric/ha-18-styled.svg', 'Ayla Instant Slip-On in Charcoal', 1),
  ('p-ayla-instant', 'HA-18', '/img/fabric/ha-18-flat.svg', 'Ayla Instant Slip-On in Charcoal', 2),
  ('p-ayla-instant', 'HA-18', '/img/fabric/ha-18-macro.svg', 'Ayla Instant Slip-On in Charcoal', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-ayla-instant', 'HA-02', 12, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-ayla-instant' and colorway_code = 'HA-02';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-ayla-instant', 'HA-02', '/img/fabric/ha-02-drape.svg', 'Ayla Instant Slip-On in Ink Rose', 0),
  ('p-ayla-instant', 'HA-02', '/img/fabric/ha-02-styled.svg', 'Ayla Instant Slip-On in Ink Rose', 1),
  ('p-ayla-instant', 'HA-02', '/img/fabric/ha-02-flat.svg', 'Ayla Instant Slip-On in Ink Rose', 2),
  ('p-ayla-instant', 'HA-02', '/img/fabric/ha-02-macro.svg', 'Ayla Instant Slip-On in Ink Rose', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-ayla-instant', 'HA-04', 26, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-ayla-instant' and colorway_code = 'HA-04';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-ayla-instant', 'HA-04', '/img/fabric/ha-04-drape.svg', 'Ayla Instant Slip-On in Jade Deep', 0),
  ('p-ayla-instant', 'HA-04', '/img/fabric/ha-04-styled.svg', 'Ayla Instant Slip-On in Jade Deep', 1),
  ('p-ayla-instant', 'HA-04', '/img/fabric/ha-04-flat.svg', 'Ayla Instant Slip-On in Jade Deep', 2),
  ('p-ayla-instant', 'HA-04', '/img/fabric/ha-04-macro.svg', 'Ayla Instant Slip-On in Jade Deep', 3);

-- Rida Georgette Shimmer
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-rida-georgette', 'rida-georgette-shimmer', 'Rida Georgette Shimmer', 'Lustre you have to look twice to see', 'A metallic filament run every fourth warp yarn, so the shimmer breaks up across the folds instead of sitting on the surface as a sheet. Reads as occasion wear without reading as costume.',
  'occasion-satin', 'rectangle', array['occasion', 'eid', 'wedding']::text[],
  1299, 1799, 'Shimmer georgette', '96% polyester georgette, 4% metallic filament', 'plain', 78,
  72, 195, '', 102,
  'Surat, Gujarat', 'Hand wash cold, separately for the first wash.', array['Metallic filament woven in, not printed on', 'Sheer — pair with a matching under-cap', 'Catches light in the folds only']::text[], '',
  false, false, false,
  false, true, 980
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-rida-georgette', 'HA-12', 14, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-rida-georgette' and colorway_code = 'HA-12';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-rida-georgette', 'HA-12', '/img/fabric/ha-12-drape.svg', 'Rida Georgette Shimmer in Blush Pearl', 0),
  ('p-rida-georgette', 'HA-12', '/img/fabric/ha-12-styled.svg', 'Rida Georgette Shimmer in Blush Pearl', 1),
  ('p-rida-georgette', 'HA-12', '/img/fabric/ha-12-flat.svg', 'Rida Georgette Shimmer in Blush Pearl', 2),
  ('p-rida-georgette', 'HA-12', '/img/fabric/ha-12-macro.svg', 'Rida Georgette Shimmer in Blush Pearl', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-rida-georgette', 'HA-09', 9, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-rida-georgette' and colorway_code = 'HA-09';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-rida-georgette', 'HA-09', '/img/fabric/ha-09-drape.svg', 'Rida Georgette Shimmer in Saffron', 0),
  ('p-rida-georgette', 'HA-09', '/img/fabric/ha-09-styled.svg', 'Rida Georgette Shimmer in Saffron', 1),
  ('p-rida-georgette', 'HA-09', '/img/fabric/ha-09-flat.svg', 'Rida Georgette Shimmer in Saffron', 2),
  ('p-rida-georgette', 'HA-09', '/img/fabric/ha-09-macro.svg', 'Rida Georgette Shimmer in Saffron', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-rida-georgette', 'HA-13', 18, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-rida-georgette' and colorway_code = 'HA-13';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-rida-georgette', 'HA-13', '/img/fabric/ha-13-drape.svg', 'Rida Georgette Shimmer in Lavender Haze', 0),
  ('p-rida-georgette', 'HA-13', '/img/fabric/ha-13-styled.svg', 'Rida Georgette Shimmer in Lavender Haze', 1),
  ('p-rida-georgette', 'HA-13', '/img/fabric/ha-13-flat.svg', 'Rida Georgette Shimmer in Lavender Haze', 2),
  ('p-rida-georgette', 'HA-13', '/img/fabric/ha-13-macro.svg', 'Rida Georgette Shimmer in Lavender Haze', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-rida-georgette', 'HA-22', 11, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-rida-georgette' and colorway_code = 'HA-22';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-rida-georgette', 'HA-22', '/img/fabric/ha-22-drape.svg', 'Rida Georgette Shimmer in Rose Gold', 0),
  ('p-rida-georgette', 'HA-22', '/img/fabric/ha-22-styled.svg', 'Rida Georgette Shimmer in Rose Gold', 1),
  ('p-rida-georgette', 'HA-22', '/img/fabric/ha-22-flat.svg', 'Rida Georgette Shimmer in Rose Gold', 2),
  ('p-rida-georgette', 'HA-22', '/img/fabric/ha-22-macro.svg', 'Rida Georgette Shimmer in Rose Gold', 3);

-- Sabr Cotton Voile
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-sabr-voile', 'sabr-cotton-voile', 'Sabr Cotton Voile', 'Plain weave, nothing hidden', 'A square, worn folded to a triangle — the way most of our mothers wore theirs. Combed cotton so there is no fuzz on the surface, and a crisp enough hand to hold a fold you set.',
  'everyday-modal', 'square', array['everyday', 'summer']::text[],
  649, 899, 'Cotton voile', '100% combed cotton', 'plain', 72,
  110, 110, '', 96,
  'Erode, Tamil Nadu', 'Machine wash warm. Iron on cotton setting.', array['Square cut, 110 × 110 cm', 'Holds a fold you set by hand', 'Takes a hot iron']::text[], '',
  false, false, false,
  false, true, 2870
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-sabr-voile', 'HA-19', 61, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-sabr-voile' and colorway_code = 'HA-19';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-sabr-voile', 'HA-19', '/img/fabric/ha-19-drape.svg', 'Sabr Cotton Voile in Pearl White', 0),
  ('p-sabr-voile', 'HA-19', '/img/fabric/ha-19-styled.svg', 'Sabr Cotton Voile in Pearl White', 1),
  ('p-sabr-voile', 'HA-19', '/img/fabric/ha-19-flat.svg', 'Sabr Cotton Voile in Pearl White', 2),
  ('p-sabr-voile', 'HA-19', '/img/fabric/ha-19-macro.svg', 'Sabr Cotton Voile in Pearl White', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-sabr-voile', 'HA-06', 44, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-sabr-voile' and colorway_code = 'HA-06';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-sabr-voile', 'HA-06', '/img/fabric/ha-06-drape.svg', 'Sabr Cotton Voile in Oat Chalk', 0),
  ('p-sabr-voile', 'HA-06', '/img/fabric/ha-06-styled.svg', 'Sabr Cotton Voile in Oat Chalk', 1),
  ('p-sabr-voile', 'HA-06', '/img/fabric/ha-06-flat.svg', 'Sabr Cotton Voile in Oat Chalk', 2),
  ('p-sabr-voile', 'HA-06', '/img/fabric/ha-06-macro.svg', 'Sabr Cotton Voile in Oat Chalk', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-sabr-voile', 'HA-14', 22, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-sabr-voile' and colorway_code = 'HA-14';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-sabr-voile', 'HA-14', '/img/fabric/ha-14-drape.svg', 'Sabr Cotton Voile in Steel Blue', 0),
  ('p-sabr-voile', 'HA-14', '/img/fabric/ha-14-styled.svg', 'Sabr Cotton Voile in Steel Blue', 1),
  ('p-sabr-voile', 'HA-14', '/img/fabric/ha-14-flat.svg', 'Sabr Cotton Voile in Steel Blue', 2),
  ('p-sabr-voile', 'HA-14', '/img/fabric/ha-14-macro.svg', 'Sabr Cotton Voile in Steel Blue', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-sabr-voile', 'HA-05', 30, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-sabr-voile' and colorway_code = 'HA-05';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-sabr-voile', 'HA-05', '/img/fabric/ha-05-drape.svg', 'Sabr Cotton Voile in Sage Mist', 0),
  ('p-sabr-voile', 'HA-05', '/img/fabric/ha-05-styled.svg', 'Sabr Cotton Voile in Sage Mist', 1),
  ('p-sabr-voile', 'HA-05', '/img/fabric/ha-05-flat.svg', 'Sabr Cotton Voile in Sage Mist', 2),
  ('p-sabr-voile', 'HA-05', '/img/fabric/ha-05-macro.svg', 'Sabr Cotton Voile in Sage Mist', 3);

-- Layla Bridal Shawl
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-layla-bridal', 'layla-bridal-shawl', 'Layla Bridal Shawl', 'Hand-set, made to order', 'Nine to fourteen days of bead work by one karigar, on silk tulle light enough that the weight you feel is the embellishment and not the cloth. Made to order — we cut nothing before you ask.',
  'bridal-atelier', 'shawl', array['wedding', 'occasion']::text[],
  6499, 8999, 'Silk-blend tulle with hand embellishment', '70% silk, 30% nylon tulle; glass bead and sequin work', 'tulle', 48,
  95, 220, '', 310,
  'Hand-worked in Lucknow, Uttar Pradesh', 'Dry clean only. Store flat, rolled in tissue.', array['Made to order: ships in 12–16 days', 'Every piece is signed by its karigar', 'Bead placement varies slightly by hand — that is the point']::text[], '',
  false, true, false,
  true, true, 132
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-layla-bridal', 'HA-12', 3, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-layla-bridal' and colorway_code = 'HA-12';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-layla-bridal', 'HA-12', '/img/fabric/ha-12-drape.svg', 'Layla Bridal Shawl in Blush Pearl', 0),
  ('p-layla-bridal', 'HA-12', '/img/fabric/ha-12-styled.svg', 'Layla Bridal Shawl in Blush Pearl', 1),
  ('p-layla-bridal', 'HA-12', '/img/fabric/ha-12-flat.svg', 'Layla Bridal Shawl in Blush Pearl', 2),
  ('p-layla-bridal', 'HA-12', '/img/fabric/ha-12-macro.svg', 'Layla Bridal Shawl in Blush Pearl', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-layla-bridal', 'HA-19', 4, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-layla-bridal' and colorway_code = 'HA-19';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-layla-bridal', 'HA-19', '/img/fabric/ha-19-drape.svg', 'Layla Bridal Shawl in Pearl White', 0),
  ('p-layla-bridal', 'HA-19', '/img/fabric/ha-19-styled.svg', 'Layla Bridal Shawl in Pearl White', 1),
  ('p-layla-bridal', 'HA-19', '/img/fabric/ha-19-flat.svg', 'Layla Bridal Shawl in Pearl White', 2),
  ('p-layla-bridal', 'HA-19', '/img/fabric/ha-19-macro.svg', 'Layla Bridal Shawl in Pearl White', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-layla-bridal', 'HA-22', 2, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-layla-bridal' and colorway_code = 'HA-22';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-layla-bridal', 'HA-22', '/img/fabric/ha-22-drape.svg', 'Layla Bridal Shawl in Rose Gold', 0),
  ('p-layla-bridal', 'HA-22', '/img/fabric/ha-22-styled.svg', 'Layla Bridal Shawl in Rose Gold', 1),
  ('p-layla-bridal', 'HA-22', '/img/fabric/ha-22-flat.svg', 'Layla Bridal Shawl in Rose Gold', 2),
  ('p-layla-bridal', 'HA-22', '/img/fabric/ha-22-macro.svg', 'Layla Bridal Shawl in Rose Gold', 3);

-- Hana Chiffon Square
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-hana-square', 'hana-chiffon-square', 'Hana Chiffon Square', 'The travel square', 'Sixty-four grams, folds to the size of a phone, and dries in the time it takes to shower. Sheer, so it wants a cap — but it is the one that lives in the bag permanently.',
  'crinkle-chiffon', 'square', array['everyday', 'travel']::text[],
  599, 799, 'Chiffon', '100% polyester chiffon', 'plain', 58,
  105, 105, '', 64,
  'Surat, Gujarat', 'Hand wash cold. Drip dry — dries in minutes.', array['64 g — folds to phone size', 'Dries in minutes', 'Sheer: wear with an under-cap']::text[], '',
  false, false, false,
  false, true, 3410
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-hana-square', 'HA-03', 36, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-hana-square' and colorway_code = 'HA-03';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-hana-square', 'HA-03', '/img/fabric/ha-03-drape.svg', 'Hana Chiffon Square in Aura Rose', 0),
  ('p-hana-square', 'HA-03', '/img/fabric/ha-03-styled.svg', 'Hana Chiffon Square in Aura Rose', 1),
  ('p-hana-square', 'HA-03', '/img/fabric/ha-03-flat.svg', 'Hana Chiffon Square in Aura Rose', 2),
  ('p-hana-square', 'HA-03', '/img/fabric/ha-03-macro.svg', 'Hana Chiffon Square in Aura Rose', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-hana-square', 'HA-16', 28, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-hana-square' and colorway_code = 'HA-16';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-hana-square', 'HA-16', '/img/fabric/ha-16-drape.svg', 'Hana Chiffon Square in Teal Slate', 0),
  ('p-hana-square', 'HA-16', '/img/fabric/ha-16-styled.svg', 'Hana Chiffon Square in Teal Slate', 1),
  ('p-hana-square', 'HA-16', '/img/fabric/ha-16-flat.svg', 'Hana Chiffon Square in Teal Slate', 2),
  ('p-hana-square', 'HA-16', '/img/fabric/ha-16-macro.svg', 'Hana Chiffon Square in Teal Slate', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-hana-square', 'HA-13', 31, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-hana-square' and colorway_code = 'HA-13';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-hana-square', 'HA-13', '/img/fabric/ha-13-drape.svg', 'Hana Chiffon Square in Lavender Haze', 0),
  ('p-hana-square', 'HA-13', '/img/fabric/ha-13-styled.svg', 'Hana Chiffon Square in Lavender Haze', 1),
  ('p-hana-square', 'HA-13', '/img/fabric/ha-13-flat.svg', 'Hana Chiffon Square in Lavender Haze', 2),
  ('p-hana-square', 'HA-13', '/img/fabric/ha-13-macro.svg', 'Hana Chiffon Square in Lavender Haze', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-hana-square', 'HA-19', 25, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-hana-square' and colorway_code = 'HA-19';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-hana-square', 'HA-19', '/img/fabric/ha-19-drape.svg', 'Hana Chiffon Square in Pearl White', 0),
  ('p-hana-square', 'HA-19', '/img/fabric/ha-19-styled.svg', 'Hana Chiffon Square in Pearl White', 1),
  ('p-hana-square', 'HA-19', '/img/fabric/ha-19-flat.svg', 'Hana Chiffon Square in Pearl White', 2),
  ('p-hana-square', 'HA-19', '/img/fabric/ha-19-macro.svg', 'Hana Chiffon Square in Pearl White', 3);

-- Amara Turkish Cotton
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-amara-turkish', 'amara-turkish-cotton', 'Amara Turkish Cotton', 'Structure, if you like a shape', 'A firmer twill that holds an architectural shape rather than collapsing around the shoulders. If every soft hijab has ever felt shapeless on you, this is the correction.',
  'everyday-modal', 'rectangle', array['work', 'occasion', 'everyday']::text[],
  1149, 1599, 'Turkish combed cotton', '100% Turkish combed cotton', 'twill', 145,
  78, 195, '', 172,
  'Woven in Denizli, Türkiye', 'Machine wash cold. Warm iron if you want a sharper edge.', array['Holds a structured shape', 'Fully opaque', 'Firm hand — softens over ten washes']::text[], '',
  false, false, false,
  false, true, 1640
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-amara-turkish', 'HA-08', 19, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-amara-turkish' and colorway_code = 'HA-08';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-amara-turkish', 'HA-08', '/img/fabric/ha-08-drape.svg', 'Amara Turkish Cotton in Camel', 0),
  ('p-amara-turkish', 'HA-08', '/img/fabric/ha-08-styled.svg', 'Amara Turkish Cotton in Camel', 1),
  ('p-amara-turkish', 'HA-08', '/img/fabric/ha-08-flat.svg', 'Amara Turkish Cotton in Camel', 2),
  ('p-amara-turkish', 'HA-08', '/img/fabric/ha-08-macro.svg', 'Amara Turkish Cotton in Camel', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-amara-turkish', 'HA-17', 15, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-amara-turkish' and colorway_code = 'HA-17';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-amara-turkish', 'HA-17', '/img/fabric/ha-17-drape.svg', 'Amara Turkish Cotton in Olive Bronze', 0),
  ('p-amara-turkish', 'HA-17', '/img/fabric/ha-17-styled.svg', 'Amara Turkish Cotton in Olive Bronze', 1),
  ('p-amara-turkish', 'HA-17', '/img/fabric/ha-17-flat.svg', 'Amara Turkish Cotton in Olive Bronze', 2),
  ('p-amara-turkish', 'HA-17', '/img/fabric/ha-17-macro.svg', 'Amara Turkish Cotton in Olive Bronze', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-amara-turkish', 'HA-21', 23, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-amara-turkish' and colorway_code = 'HA-21';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-amara-turkish', 'HA-21', '/img/fabric/ha-21-drape.svg', 'Amara Turkish Cotton in Mocha', 0),
  ('p-amara-turkish', 'HA-21', '/img/fabric/ha-21-styled.svg', 'Amara Turkish Cotton in Mocha', 1),
  ('p-amara-turkish', 'HA-21', '/img/fabric/ha-21-flat.svg', 'Amara Turkish Cotton in Mocha', 2),
  ('p-amara-turkish', 'HA-21', '/img/fabric/ha-21-macro.svg', 'Amara Turkish Cotton in Mocha', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-amara-turkish', 'HA-18', 27, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-amara-turkish' and colorway_code = 'HA-18';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-amara-turkish', 'HA-18', '/img/fabric/ha-18-drape.svg', 'Amara Turkish Cotton in Charcoal', 0),
  ('p-amara-turkish', 'HA-18', '/img/fabric/ha-18-styled.svg', 'Amara Turkish Cotton in Charcoal', 1),
  ('p-amara-turkish', 'HA-18', '/img/fabric/ha-18-flat.svg', 'Amara Turkish Cotton in Charcoal', 2),
  ('p-amara-turkish', 'HA-18', '/img/fabric/ha-18-macro.svg', 'Amara Turkish Cotton in Charcoal', 3);

-- Dua Pleated Chiffon
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-dua-pleated', 'dua-pleated-chiffon', 'Dua Pleated Chiffon', 'Pleats set at the mill', 'Four-millimetre knife pleats heat-set permanently, so the cloth arrives narrow and opens as you drape it. The pleats catch light along every edge, which does most of the styling for you.',
  'crinkle-chiffon', 'rectangle', array['occasion', 'eid', 'work']::text[],
  1099, 1499, 'Heat-pleated chiffon', '100% polyester, knife-pleated 4 mm', 'plain', 68,
  68, 190, 'Width relaxes to 68 cm; 24 cm pleated', 94,
  'Surat, Gujarat', 'Hand wash cold. Hang to dry — do not fold wet.', array['Pleats are permanent', 'Opens from 24 cm to 68 cm as it drapes', 'Hang dry, never fold wet']::text[], '',
  false, false, false,
  false, true, 890
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-dua-pleated', 'HA-01', 13, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-dua-pleated' and colorway_code = 'HA-01';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-dua-pleated', 'HA-01', '/img/fabric/ha-01-drape.svg', 'Dua Pleated Chiffon in Midnight Plum', 0),
  ('p-dua-pleated', 'HA-01', '/img/fabric/ha-01-styled.svg', 'Dua Pleated Chiffon in Midnight Plum', 1),
  ('p-dua-pleated', 'HA-01', '/img/fabric/ha-01-flat.svg', 'Dua Pleated Chiffon in Midnight Plum', 2),
  ('p-dua-pleated', 'HA-01', '/img/fabric/ha-01-macro.svg', 'Dua Pleated Chiffon in Midnight Plum', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-dua-pleated', 'HA-07', 17, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-dua-pleated' and colorway_code = 'HA-07';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-dua-pleated', 'HA-07', '/img/fabric/ha-07-drape.svg', 'Dua Pleated Chiffon in Sand Dune', 0),
  ('p-dua-pleated', 'HA-07', '/img/fabric/ha-07-styled.svg', 'Dua Pleated Chiffon in Sand Dune', 1),
  ('p-dua-pleated', 'HA-07', '/img/fabric/ha-07-flat.svg', 'Dua Pleated Chiffon in Sand Dune', 2),
  ('p-dua-pleated', 'HA-07', '/img/fabric/ha-07-macro.svg', 'Dua Pleated Chiffon in Sand Dune', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-dua-pleated', 'HA-16', 12, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-dua-pleated' and colorway_code = 'HA-16';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-dua-pleated', 'HA-16', '/img/fabric/ha-16-drape.svg', 'Dua Pleated Chiffon in Teal Slate', 0),
  ('p-dua-pleated', 'HA-16', '/img/fabric/ha-16-styled.svg', 'Dua Pleated Chiffon in Teal Slate', 1),
  ('p-dua-pleated', 'HA-16', '/img/fabric/ha-16-flat.svg', 'Dua Pleated Chiffon in Teal Slate', 2),
  ('p-dua-pleated', 'HA-16', '/img/fabric/ha-16-macro.svg', 'Dua Pleated Chiffon in Teal Slate', 3);

-- Iman Ribbed Jersey
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-iman-ribbed', 'iman-ribbed-jersey', 'Iman Ribbed Jersey', 'Winter weight', 'Two-forty GSM with a 2×2 rib, which means it traps a layer of air against the neck. Wear it from November through February and skip the scarf entirely.',
  'jersey-instant', 'rectangle', array['everyday', 'winter', 'work']::text[],
  899, 1249, 'Ribbed jersey', '70% viscose, 25% polyester, 5% elastane', 'jersey', 240,
  72, 180, '', 214,
  'Ludhiana, Punjab', 'Machine wash cold. Do not tumble dry.', array['240 GSM — genuinely warm', '2×2 rib traps air at the neck', 'Replaces a scarf']::text[], '',
  true, false, false,
  false, true, 1310
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-iman-ribbed', 'HA-21', 21, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-iman-ribbed' and colorway_code = 'HA-21';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-iman-ribbed', 'HA-21', '/img/fabric/ha-21-drape.svg', 'Iman Ribbed Jersey in Mocha', 0),
  ('p-iman-ribbed', 'HA-21', '/img/fabric/ha-21-styled.svg', 'Iman Ribbed Jersey in Mocha', 1),
  ('p-iman-ribbed', 'HA-21', '/img/fabric/ha-21-flat.svg', 'Iman Ribbed Jersey in Mocha', 2),
  ('p-iman-ribbed', 'HA-21', '/img/fabric/ha-21-macro.svg', 'Iman Ribbed Jersey in Mocha', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-iman-ribbed', 'HA-15', 18, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-iman-ribbed' and colorway_code = 'HA-15';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-iman-ribbed', 'HA-15', '/img/fabric/ha-15-drape.svg', 'Iman Ribbed Jersey in Navy Ink', 0),
  ('p-iman-ribbed', 'HA-15', '/img/fabric/ha-15-styled.svg', 'Iman Ribbed Jersey in Navy Ink', 1),
  ('p-iman-ribbed', 'HA-15', '/img/fabric/ha-15-flat.svg', 'Iman Ribbed Jersey in Navy Ink', 2),
  ('p-iman-ribbed', 'HA-15', '/img/fabric/ha-15-macro.svg', 'Iman Ribbed Jersey in Navy Ink', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-iman-ribbed', 'HA-17', 14, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-iman-ribbed' and colorway_code = 'HA-17';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-iman-ribbed', 'HA-17', '/img/fabric/ha-17-drape.svg', 'Iman Ribbed Jersey in Olive Bronze', 0),
  ('p-iman-ribbed', 'HA-17', '/img/fabric/ha-17-styled.svg', 'Iman Ribbed Jersey in Olive Bronze', 1),
  ('p-iman-ribbed', 'HA-17', '/img/fabric/ha-17-flat.svg', 'Iman Ribbed Jersey in Olive Bronze', 2),
  ('p-iman-ribbed', 'HA-17', '/img/fabric/ha-17-macro.svg', 'Iman Ribbed Jersey in Olive Bronze', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-iman-ribbed', 'HA-20', 25, 3)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-iman-ribbed' and colorway_code = 'HA-20';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-iman-ribbed', 'HA-20', '/img/fabric/ha-20-drape.svg', 'Iman Ribbed Jersey in Onyx', 0),
  ('p-iman-ribbed', 'HA-20', '/img/fabric/ha-20-styled.svg', 'Iman Ribbed Jersey in Onyx', 1),
  ('p-iman-ribbed', 'HA-20', '/img/fabric/ha-20-flat.svg', 'Iman Ribbed Jersey in Onyx', 2),
  ('p-iman-ribbed', 'HA-20', '/img/fabric/ha-20-macro.svg', 'Iman Ribbed Jersey in Onyx', 3);

-- Nafisa Tie-Dye Modal
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-nafisa-tiedye', 'nafisa-tie-dye-modal', 'Nafisa Tie-Dye Modal', 'Dyed in small lots, tied by hand', 'Tied and dipped by hand in lots of thirty, so no two are the same. We photograph one from each lot; yours will be a cousin of the photo, not a twin.',
  'everyday-modal', 'rectangle', array['everyday', 'travel']::text[],
  1049, 1449, 'Modal', '100% modal, hand tie-dyed', 'twill', 125,
  75, 185, '', 142,
  'Dyed in Bhuj, Gujarat', 'First wash separately, cold. Colour settles after one wash.', array['No two pieces are identical', 'Photographed per lot — yours will vary', 'Bleeds slightly on the first wash']::text[], '',
  false, false, true,
  false, true, 720
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-nafisa-tiedye', 'HA-10', 11, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-nafisa-tiedye' and colorway_code = 'HA-10';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-nafisa-tiedye', 'HA-10', '/img/fabric/ha-10-drape.svg', 'Nafisa Tie-Dye Modal in Terracotta', 0),
  ('p-nafisa-tiedye', 'HA-10', '/img/fabric/ha-10-styled.svg', 'Nafisa Tie-Dye Modal in Terracotta', 1),
  ('p-nafisa-tiedye', 'HA-10', '/img/fabric/ha-10-flat.svg', 'Nafisa Tie-Dye Modal in Terracotta', 2),
  ('p-nafisa-tiedye', 'HA-10', '/img/fabric/ha-10-macro.svg', 'Nafisa Tie-Dye Modal in Terracotta', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-nafisa-tiedye', 'HA-13', 9, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-nafisa-tiedye' and colorway_code = 'HA-13';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-nafisa-tiedye', 'HA-13', '/img/fabric/ha-13-drape.svg', 'Nafisa Tie-Dye Modal in Lavender Haze', 0),
  ('p-nafisa-tiedye', 'HA-13', '/img/fabric/ha-13-styled.svg', 'Nafisa Tie-Dye Modal in Lavender Haze', 1),
  ('p-nafisa-tiedye', 'HA-13', '/img/fabric/ha-13-flat.svg', 'Nafisa Tie-Dye Modal in Lavender Haze', 2),
  ('p-nafisa-tiedye', 'HA-13', '/img/fabric/ha-13-macro.svg', 'Nafisa Tie-Dye Modal in Lavender Haze', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-nafisa-tiedye', 'HA-05', 13, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-nafisa-tiedye' and colorway_code = 'HA-05';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-nafisa-tiedye', 'HA-05', '/img/fabric/ha-05-drape.svg', 'Nafisa Tie-Dye Modal in Sage Mist', 0),
  ('p-nafisa-tiedye', 'HA-05', '/img/fabric/ha-05-styled.svg', 'Nafisa Tie-Dye Modal in Sage Mist', 1),
  ('p-nafisa-tiedye', 'HA-05', '/img/fabric/ha-05-flat.svg', 'Nafisa Tie-Dye Modal in Sage Mist', 2),
  ('p-nafisa-tiedye', 'HA-05', '/img/fabric/ha-05-macro.svg', 'Nafisa Tie-Dye Modal in Sage Mist', 3);

-- Ninja Under-Cap, set of 3
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-undercap-set', 'ninja-under-cap-set', 'Ninja Under-Cap, set of 3', 'The layer that holds everything', 'Three caps — black, nude, white — which is every under-cap you will actually reach for. Tie-back rather than elastic, so it does not press a line into your forehead by hour six.',
  'essentials', 'accessory', array['everyday']::text[],
  449, 649, 'Cotton jersey', '95% cotton, 5% elastane', 'jersey', 160,
  0, 0, 'One size, tie-back', 120,
  'Tiruppur, Tamil Nadu', 'Machine wash warm.', array['Set of three: black, nude, white', 'Tie-back, not elastic', 'No forehead line']::text[], '',
  true, false, false,
  false, true, 9120
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-undercap-set', 'HA-20', 88, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-undercap-set' and colorway_code = 'HA-20';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-undercap-set', 'HA-20', '/img/fabric/ha-20-drape.svg', 'Ninja Under-Cap, set of 3 in Onyx', 0),
  ('p-undercap-set', 'HA-20', '/img/fabric/ha-20-styled.svg', 'Ninja Under-Cap, set of 3 in Onyx', 1),
  ('p-undercap-set', 'HA-20', '/img/fabric/ha-20-flat.svg', 'Ninja Under-Cap, set of 3 in Onyx', 2),
  ('p-undercap-set', 'HA-20', '/img/fabric/ha-20-macro.svg', 'Ninja Under-Cap, set of 3 in Onyx', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-undercap-set', 'HA-07', 74, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-undercap-set' and colorway_code = 'HA-07';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-undercap-set', 'HA-07', '/img/fabric/ha-07-drape.svg', 'Ninja Under-Cap, set of 3 in Sand Dune', 0),
  ('p-undercap-set', 'HA-07', '/img/fabric/ha-07-styled.svg', 'Ninja Under-Cap, set of 3 in Sand Dune', 1),
  ('p-undercap-set', 'HA-07', '/img/fabric/ha-07-flat.svg', 'Ninja Under-Cap, set of 3 in Sand Dune', 2),
  ('p-undercap-set', 'HA-07', '/img/fabric/ha-07-macro.svg', 'Ninja Under-Cap, set of 3 in Sand Dune', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-undercap-set', 'HA-19', 66, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-undercap-set' and colorway_code = 'HA-19';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-undercap-set', 'HA-19', '/img/fabric/ha-19-drape.svg', 'Ninja Under-Cap, set of 3 in Pearl White', 0),
  ('p-undercap-set', 'HA-19', '/img/fabric/ha-19-styled.svg', 'Ninja Under-Cap, set of 3 in Pearl White', 1),
  ('p-undercap-set', 'HA-19', '/img/fabric/ha-19-flat.svg', 'Ninja Under-Cap, set of 3 in Pearl White', 2),
  ('p-undercap-set', 'HA-19', '/img/fabric/ha-19-macro.svg', 'Ninja Under-Cap, set of 3 in Pearl White', 3);

-- Magnet Pins, set of 6
insert into public.products (
  id, slug, name, tagline, description, collection_slug, style, occasion,
  price, mrp, fabric, composition, weave, gsm,
  size_w, size_l, size_note, piece_weight_g, origin, care, notes, warning,
  pinless, made_to_order, small_batch, featured, published, sold
) values (
  'p-magnet-pins', 'magnet-pins-set-6', 'Magnet Pins, set of 6', 'No holes, ever', 'Strong enough for a 240 GSM jersey, which is the only test that matters. Six pins in three finishes, in a tin that fits a pocket.',
  'essentials', 'accessory', array['everyday', 'occasion']::text[],
  299, 449, 'Neodymium magnet, enamel face', 'N42 neodymium core, brass housing, enamel face', 'none', 0,
  0, 0, '12 mm face', 34,
  'Assembled in Mumbai, Maharashtra', 'Keep away from cards and pacemakers.', array['Holds 240 GSM jersey', 'Leaves no hole', 'Not for use near pacemakers']::text[], 'Contains strong magnets. Keep away from pacemakers, cards and small children.',
  true, false, false,
  false, true, 11400
)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, tagline = excluded.tagline,
  description = excluded.description, collection_slug = excluded.collection_slug,
  style = excluded.style, occasion = excluded.occasion,
  price = excluded.price, mrp = excluded.mrp, fabric = excluded.fabric,
  composition = excluded.composition, weave = excluded.weave, gsm = excluded.gsm,
  size_w = excluded.size_w, size_l = excluded.size_l, size_note = excluded.size_note,
  piece_weight_g = excluded.piece_weight_g, origin = excluded.origin,
  care = excluded.care, notes = excluded.notes, warning = excluded.warning,
  pinless = excluded.pinless, made_to_order = excluded.made_to_order,
  small_batch = excluded.small_batch, featured = excluded.featured,
  published = excluded.published;
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-magnet-pins', 'HA-19', 120, 0)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-magnet-pins' and colorway_code = 'HA-19';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-magnet-pins', 'HA-19', '/img/fabric/ha-19-drape.svg', 'Magnet Pins, set of 6 in Pearl White', 0),
  ('p-magnet-pins', 'HA-19', '/img/fabric/ha-19-styled.svg', 'Magnet Pins, set of 6 in Pearl White', 1),
  ('p-magnet-pins', 'HA-19', '/img/fabric/ha-19-flat.svg', 'Magnet Pins, set of 6 in Pearl White', 2),
  ('p-magnet-pins', 'HA-19', '/img/fabric/ha-19-macro.svg', 'Magnet Pins, set of 6 in Pearl White', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-magnet-pins', 'HA-20', 104, 1)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-magnet-pins' and colorway_code = 'HA-20';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-magnet-pins', 'HA-20', '/img/fabric/ha-20-drape.svg', 'Magnet Pins, set of 6 in Onyx', 0),
  ('p-magnet-pins', 'HA-20', '/img/fabric/ha-20-styled.svg', 'Magnet Pins, set of 6 in Onyx', 1),
  ('p-magnet-pins', 'HA-20', '/img/fabric/ha-20-flat.svg', 'Magnet Pins, set of 6 in Onyx', 2),
  ('p-magnet-pins', 'HA-20', '/img/fabric/ha-20-macro.svg', 'Magnet Pins, set of 6 in Onyx', 3);
insert into public.product_colorways (product_id, colorway_code, stock, sort_order)
values ('p-magnet-pins', 'HA-09', 61, 2)
on conflict (product_id, colorway_code) do update set sort_order = excluded.sort_order;
delete from public.product_images where product_id = 'p-magnet-pins' and colorway_code = 'HA-09';
insert into public.product_images (product_id, colorway_code, url, alt, sort_order) values
  ('p-magnet-pins', 'HA-09', '/img/fabric/ha-09-drape.svg', 'Magnet Pins, set of 6 in Saffron', 0),
  ('p-magnet-pins', 'HA-09', '/img/fabric/ha-09-styled.svg', 'Magnet Pins, set of 6 in Saffron', 1),
  ('p-magnet-pins', 'HA-09', '/img/fabric/ha-09-flat.svg', 'Magnet Pins, set of 6 in Saffron', 2),
  ('p-magnet-pins', 'HA-09', '/img/fabric/ha-09-macro.svg', 'Magnet Pins, set of 6 in Saffron', 3);

commit;

-- Reviews and orders are intentionally NOT seeded. Ninety days of invented
-- trading history is useful in a demo and misleading in a real shop — your
-- dashboard should start empty and fill up with real orders.
